"""Enumerate the official TWSE OpenAPI surface and write a reference document.

This is the *only* discovery step that talks to the network in P1. It reads the
published API description -- nothing else -- and turns it into
``docs/reference/twse_openapi_endpoints.md`` so that later phases can choose
endpoints from a committed list instead of guessing URLs at runtime.

    uv run python scripts/explore_sources.py

Politeness, the host allowlist, and the byte ceilings all come from
``twfi.io.http``; this script cannot opt out of them.
"""

from __future__ import annotations

import json
from typing import Any

import typer

from twfi.io.hashing import sha256_bytes
from twfi.io.http import PoliteClient
from twfi.paths import repo_paths

SWAGGER_URL = "https://openapi.twse.com.tw/v1/swagger.json"

#: Terms that mark an endpoint as potentially useful for this study. Kept explicit
#: so the shortlist in the generated document is reproducible rather than a
#: judgement call made once and forgotten.
RELEVANCE_TERMS: tuple[str, ...] = (
    "綜合損益",
    "資產負債",
    "營業收入",
    "財務",
    "基本資料",
    "股利",
    "每月",
    "月營收",
    "個股日成交",
)

app = typer.Typer(add_completion=False, help=__doc__)


def _resolve_ref(document: dict[str, Any], ref: str) -> dict[str, Any]:
    """Resolve a local ``$ref`` pointer, returning ``{}`` if it cannot be followed."""
    if not ref.startswith("#/"):
        return {}
    node: Any = document
    for part in ref.removeprefix("#/").split("/"):
        if not isinstance(node, dict) or part not in node:
            return {}
        node = node[part]
    return node if isinstance(node, dict) else {}


def _schema_for_operation(document: dict[str, Any], operation: dict[str, Any]) -> dict[str, Any]:
    """Best-effort extraction of the 200-response schema (Swagger 2.0 or OpenAPI 3.x)."""
    responses = operation.get("responses")
    if not isinstance(responses, dict):
        return {}
    ok = responses.get("200") or responses.get(200) or {}
    if not isinstance(ok, dict):
        return {}

    schema = ok.get("schema")  # Swagger 2.0
    if schema is None:  # OpenAPI 3.x
        content = ok.get("content")
        if isinstance(content, dict):
            for media in ("application/json", "*/*"):
                if isinstance(content.get(media), dict):
                    schema = content[media].get("schema")
                    break
    if not isinstance(schema, dict):
        return {}

    if "$ref" in schema:
        schema = _resolve_ref(document, str(schema["$ref"]))
    if schema.get("type") == "array" and isinstance(schema.get("items"), dict):
        items = schema["items"]
        if "$ref" in items:
            items = _resolve_ref(document, str(items["$ref"]))
        schema = items if isinstance(items, dict) else {}
    return schema


def _field_names(schema: dict[str, Any]) -> list[str]:
    properties = schema.get("properties")
    return sorted(properties) if isinstance(properties, dict) else []


def _is_relevant(path: str, summary: str, fields: list[str]) -> bool:
    haystack = " ".join([path, summary, *fields])
    return any(term in haystack for term in RELEVANCE_TERMS)


def _render(document: dict[str, Any], *, url: str, digest: str, retrieved_at: str) -> str:
    info_field = document.get("info")
    paths_field = document.get("paths")
    info: dict[str, Any] = info_field if isinstance(info_field, dict) else {}
    paths: dict[str, Any] = paths_field if isinstance(paths_field, dict) else {}

    rows: list[tuple[str, str, str, list[str]]] = []
    for path, methods in sorted(paths.items()):
        if not isinstance(methods, dict):
            continue
        for method, operation in sorted(methods.items()):
            if method.lower() not in {"get", "post"} or not isinstance(operation, dict):
                continue
            summary = str(operation.get("summary") or operation.get("description") or "").strip()
            fields = _field_names(_schema_for_operation(document, operation))
            rows.append((path, method.upper(), summary, fields))

    relevant = [row for row in rows if _is_relevant(row[0], row[2], row[3])]

    lines: list[str] = [
        "# TWSE OpenAPI endpoint reference",
        "",
        "> Generated by `scripts/explore_sources.py`. Do not edit by hand -- re-run the script.",
        "",
        f"- source: `{url}`",
        f"- sha256: `{digest}`",
        f"- retrieved_at: `{retrieved_at}`",
        f"- title: {info.get('title', '(none)')}",
        f"- api version: {info.get('version', '(none)')}",
        f"- endpoints discovered: **{len(rows)}**",
        f"- shortlisted as potentially relevant: **{len(relevant)}**",
        "",
        "This file records what the official API *offers*. Which endpoints the study",
        "actually uses is declared in `data/manifests/structured.yaml`.",
        "",
        "## Shortlist for this study",
        "",
        "Matched on: " + ", ".join(f"`{term}`" for term in RELEVANCE_TERMS),
        "",
        "| path | method | summary | fields |",
        "|---|---|---|---|",
    ]
    for path, method, summary, fields in relevant:
        preview = ", ".join(f"`{name}`" for name in fields[:8])
        if len(fields) > 8:
            preview += f", … (+{len(fields) - 8})"
        lines.append(f"| `{path}` | {method} | {summary or '—'} | {preview or '—'} |")

    lines += [
        "",
        "## All endpoints",
        "",
        "| path | method | summary | field count |",
        "|---|---|---|---|",
    ]
    for path, method, summary, fields in rows:
        lines.append(f"| `{path}` | {method} | {summary or '—'} | {len(fields)} |")

    lines.append("")
    return "\n".join(lines)


@app.command()
def main(
    url: str = typer.Option(SWAGGER_URL, help="Official API description to read."),
    keep_raw: bool = typer.Option(
        True, help="Also store the raw JSON under data/raw/ (git-ignored)."
    ),
) -> None:
    """Fetch the API description and regenerate the endpoint reference."""
    paths = repo_paths()
    paths.ensure_generated_dirs()

    with PoliteClient() as client:
        payload, result = client.get_bytes(url)
        network = client.snapshot()

    document = json.loads(payload)
    if not isinstance(document, dict):
        raise typer.BadParameter(f"{url} did not return a JSON object")

    digest = sha256_bytes(payload)
    output = paths.docs / "reference" / "twse_openapi_endpoints.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        _render(document, url=url, digest=digest, retrieved_at=result.retrieved_at),
        encoding="utf-8",
    )

    if keep_raw:
        raw_dir = paths.raw / "structured"
        raw_dir.mkdir(parents=True, exist_ok=True)
        raw_path = raw_dir / "twse_openapi_swagger.json"
        raw_path.write_bytes(payload)
        typer.echo(f"raw   : {raw_path}")

    typer.echo(f"source: {url}")
    typer.echo(f"sha256: {digest}")
    typer.echo(f"bytes : {result.num_bytes}")
    typer.echo(f"wrote : {output.relative_to(paths.root)}")
    typer.echo("network: " + json.dumps(network, ensure_ascii=False, sort_keys=True))


def _entrypoint() -> None:
    app()


if __name__ == "__main__":
    _entrypoint()
